# Generated by Django 3.0.2 on 2020-01-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbase',
            name='event_period',
            field=models.CharField(blank=True, choices=[('DAY', 'Ежедневное'), ('MTH', 'Ежемесячное'), ('YER', 'Ежегодное')], max_length=10, null=True),
        ),
    ]
